# -----------------------------------------------------------------------------
# Fascio elettronico centrato, gaussiano e divergente
# -----------------------------------------------------------------------------
# Elettroni monocromatici da 1 GeV:
# - spot trasverso gaussiano
# - fascio centrato
# - piccola divergenza angolare
# -----------------------------------------------------------------------------

/run/initialize
/analysis/setFileName beam_electron_gaus.root

#/random/setSeeds 12345 67890

/gps/particle e-

# Distribuzione spaziale del fascio
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/centre 0 0 -25 cm
/gps/pos/sigma_x 2.5 mm
/gps/pos/sigma_y 2.5 mm

# Va applicata questa rotazione perché GPS 
# considera positivo l'asse -Z 
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0

# Distribuzione angolare divergente
/gps/ang/type beam2d
/gps/ang/sigma_x 5.0 deg
/gps/ang/sigma_y 5.0 deg

# Energia Gaussiana
/gps/ene/type Gauss
/gps/ene/mono 1 GeV
/gps/ene/sigma 100. MeV

/run/printProgress 1000
/run/beamOn 1000