# -----------------------------------------------------------------------------
# Configurazione di default del generatore
# -----------------------------------------------------------------------------
# Elettroni da 1 GeV, puntiformi, centrati, incidenti lungo +z.
# Questa macro è pensata per essere eseguita automaticamente all'avvio.
# -----------------------------------------------------------------------------

/gps/particle e-

/gps/pos/type Point
/gps/pos/centre 0 0 -25 cm

/gps/direction 0 0 1

/gps/ene/type Mono
/gps/ene/mono 1 GeV